apiVersion: v1
kind: ConfigMap
metadata:
  name: devpulse-config
  namespace: devpulse-ai
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "postgres"
  REDIS_HOST: "redis"
  KAFKA_HOST: "kafka:9092"